/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arnavgohil
 */
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class DELETE extends javax.swing.JFrame {
int flag = 0 ;
    /**
     * Creates new form DELETE
     */
    public DELETE() {
        initComponents();
        t1.setVisible(false);
        l1.setVisible(false);
        bb.setVisible(false);
        s1.setVisible(false);
        s2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        bb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JSeparator();
        s2 = new javax.swing.JSeparator();
        studLL = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        facLL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 184, 26));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 114, -1));

        bb.setText("→");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 43, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dtumini.png"))); // NOI18N
        jLabel1.setToolTipText("Home");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 14, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 14, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DELETE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 14, -1, -1));

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setForeground(new java.awt.Color(102, 204, 255));
        jPanel2.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, -1));

        s2.setBackground(new java.awt.Color(255, 255, 255));
        s2.setForeground(new java.awt.Color(102, 204, 255));
        jPanel2.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        studLL.setBackground(new java.awt.Color(0, 153, 255));
        studLL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studLLMouseClicked(evt);
            }
        });

        jLabel3.setText("STUDENT");

        javax.swing.GroupLayout studLLLayout = new javax.swing.GroupLayout(studLL);
        studLL.setLayout(studLLLayout);
        studLLLayout.setHorizontalGroup(
            studLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studLLLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        studLLLayout.setVerticalGroup(
            studLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studLLLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(studLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 30));

        facLL.setBackground(new java.awt.Color(0, 153, 255));
        facLL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facLLMouseClicked(evt);
            }
        });

        jLabel4.setText("FACULTY");

        javax.swing.GroupLayout facLLLayout = new javax.swing.GroupLayout(facLL);
        facLL.setLayout(facLLLayout);
        facLLLayout.setHorizontalGroup(
            facLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facLLLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(68, 68, 68))
        );
        facLLLayout.setVerticalGroup(
            facLLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facLLLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(facLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 0, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        String str = t1.getText();
        String query = "";
        if(flag == 1)
            query = "DELETE FROM STUDENTS WHERE ADMN_NO = " + str + " ;";
        else if(flag == 2)
            query = "DELETE FROM FACULTY WHERE FAC_ID = " + str + " ;";
        
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/university", "root", "agat9191");
            Statement stmt = conn.createStatement();
            String qr = "";
            if(flag == 1)
                qr = "SELECT NAME FROM STUDENTS WHERE ADMN_NO = " + str + " ;";
            else if(flag == 2)
                qr = "SELECT NAME FROM FACULTY WHERE FAC_ID = " + str + " ;";
            
            ResultSet rs = stmt.executeQuery(qr);            
            rs.next();
            qr = rs.getString(1).toUpperCase();
            int rep =  JOptionPane.showConfirmDialog(null, "Are You sure you want to delete " + qr + " ?", "DELETE ?",JOptionPane.YES_NO_OPTION);
            if(rep == JOptionPane.YES_OPTION)
            {
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "DELETED!");
            }
            
            stmt.close();
            conn.close();
           
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "INVALID!");
                Logger.getLogger(DELETE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bbActionPerformed

    private void studLLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studLLMouseClicked
        // TODO add your handling code here:
        setColor(studLL);
        resetColor(facLL);
        t1.setVisible(true);
        l1.setVisible(true);
        bb.setVisible(true);
        s1.setVisible(true);
        s2.setVisible(false);
        l1.setText("Enter Admn No.");
        flag = 1 ;
    }//GEN-LAST:event_studLLMouseClicked

    private void facLLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facLLMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        resetColor(studLL);
        setColor(facLL);
        t1.setVisible(true);
        l1.setVisible(true);
        bb.setVisible(true);
        s1.setVisible(false);
        s2.setVisible(true);
        l1.setText("Enter Faculty Id");
        flag = 2 ;
    }//GEN-LAST:event_facLLMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(238,238,238));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(0,153,255));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel facLL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JSeparator s1;
    private javax.swing.JSeparator s2;
    private javax.swing.JPanel studLL;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
